### ISSUE TITLE
DbContextFactory injection instead of DbContext in the Blazor Server

### ISSUE THREAD

**Issue by xenbill** [markjprice/cs10dotnet6#17]
When I am injecting dbContext (page740) and I am trying to add or update Customers 
I am getting an exception 

`Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'Xenbill.Shared.NorthwindContext'.
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
`

After a little research I injected dbContextFactory instead of  DbContext  directly.
I create   new instances of dbContext every time I use NorthwindService ( which is Transient) .

Is this ok ? 

btw Thx for this great book !!

**Comment by markjprice** [comment]
I will try to investigate this issue next weekend. My initial thought is that, yes, your fix is the proper way to go.

**Comment by CodeMerchant** [comment]
Hi, using `builder.Service.AddDbContext<NorthwindContext>(ServiceLifetime.Transient);` helped me solve the issue. 
This is where I found the fix and explanation [](https://stackoverflow.com/questions/48767910/entity-framework-core-a-second-operation-started-on-this-context-before-a-previ)

**Comment by CodeMerchant** [comment]
> Hi, using `builder.Service.AddDbContext<NorthwindContext>(ServiceLifetime.Transient);` helped me solve the issue. This is where I found the fix and explanation - https://stackoverflow.com/questions/48767910/entity-framework-core-a-second-operation-started-on-this-context-before-a-previ

Just noticed that the errors aren't the same. I encountered an error on page 740 and assumed it was the same. Should I delete my "fix"?
