### ISSUE TITLE
Building a weather service using minimal APIs - ERROR: A path base can only be configured using IApplicationBuilder.UsePathBase().

### ISSUE THREAD

**Issue by ntsiatinis** [markjprice/cs10dotnet6#49]
Just came across the following issue on or around page 712 when building the minimal API web service.

Using VS Code, when following the instructions and then running the API I received the following error

`Unhandled exception. System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)`

Tweaking the launchSettings.json to

 "applicationUrl": "https://localhost:5003/",
 "launchUrl": "api/weather",

got around the issue and allowed the API to start up.

**Comment by markjprice** [comment]
Thanks, Nick. I have added an erratum for this issue:
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-712---building-a-weather-service-using-minimal-apis

**Comment by douglasg14b** [comment]
@markjprice That's a dead link....

**Comment by markjprice** [comment]
I moved the errata page. Here's an updated link:
https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#page-712---building-a-weather-service-using-minimal-apis
